Homework 04
NinaPythonBasic/ForPythonBasic pull request #4
Opened 2022-12-05 23:16 UTC by NinaPythonBasic

- SQLAlchemy
- Work with the network
- Async functions

2022-12-21 14:30 UTC, mahenzon commented on homework_04/main.py
> +async def create_posts_for_user(
так как функция нигде больше не используется, её можно и удалить. понимаю, что жалко написанный код удалять, но если оно реально в ближайшем будущем не пригодится (а в домашках не пригодится), то можно смело удалять

2022-12-21 14:35 UTC, mahenzon commented on homework_04/main.py
> +async def create_user(session: AsyncSession, username: str, email: str) -> User:
и эту функцию тоже можно снести

2022-12-21 14:36 UTC, mahenzon commented on homework_04/main.py
> +        user: Union[User, None] = await get_user_by_id(session, post_data["userId"])
тут не нужно искать пользователя

2022-12-21 14:36 UTC, mahenzon commented on homework_04/main.py
> +            user_id=1,
это значение неверно

2022-12-21 14:37 UTC, mahenzon commented on homework_04/main.py
> +            user=user,
тут можно просто не указывать

2022-12-21 14:38 UTC, mahenzon commented on homework_04/main.py
> +    session.add_all(posts)
тут можно не делать этого, так как выше уже выполнено `session.add(post)`

2022-12-21 14:41 UTC, mahenzon commented on homework_04/models.py
> +class Base:
круто, что создан базовый класс

2022-12-21 14:42 UTC, mahenzon requested changes
Отличная работа.
Нужно поправить выставление связи с юзером (у поста). 
В остальном супер

2022-12-21 21:31 UTC, NinaPythonBasic commented
Исправила выставление posts.user_id

2022-12-30 01:46 UTC, mahenzon approved these changes

2023-01-16 19:37 UTC, merged